apiRules:
  - exclude:
      uidRegex: ^Telerik\.Charting
  - exclude:
      uidRegex: ^Telerik\.Licensing
  - exclude:
      uidRegex: ^Telerik\.Web\.Apoc\.Layout
  - exclude:
      uidRegex: ^Telerik\.Web\.Apoc\.Render
  - exclude:
      uidRegex: ^Telerik\.Web\.Extensions
  - exclude:
      uidRegex: ^Telerik\.Web\.UI\.AIPrompt
  - exclude:
      uidRegex: ^Telerik\.Web\.UI\.Barcode\.PDF417ClassLibrary
  - exclude:
      uidRegex: ^Telerik\.Web\.UI\.ButtonNS\.JavaScriptSerialization
  - exclude:
      uidRegex: ^Telerik\.Web\.UI\.ButtonRendering
  - exclude:
      uidRegex: ^Telerik\.Web\.UI\.ButtonRendering\.Lightweight
  - exclude:
      uidRegex: ^Telerik\.Web\.UI\.Common\.Helpers
  - exclude:
      uidRegex: ^Telerik\.Web\.UI\.Common\.SerializeJS
  - exclude:
      uidRegex: ^Telerik\.Web\.UI\.HtmlChart\.JavaScriptConverters\.Bullet
  - exclude:
      uidRegex: ^Telerik\.Web\.UI\.HtmlChart\.JavaScriptConverters\.SeriesItems
  - exclude:
      uidRegex: ^Telerik\.Web\.UI\.Menu\.Renderers
  - exclude:
      uidRegex: ^Telerik\.Web\.UI\.Notification\.Renderers
  - exclude:
      uidRegex: ^Telerik\.Web\.UI\.PanelBar\.Renderers
  - exclude:
      uidRegex: ^Telerik\.Web\.UI\.Renderers
  - exclude:
      uidRegex: ^Telerik\.Web\.UI\.Renderers\.CloudUpload
  - exclude:
      uidRegex: ^Telerik\.Web\.UI\.ListBox\.Renderers
  - exclude:
      uidRegex: ^Telerik\.Web\.UI\.TreeView\.Renderers